apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: connector-demo
build:
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
  artifacts:
    - image: europe-west1-docker.pkg.dev/deepomatic-160015/docker-main/connector-demo
      platforms: ["linux/amd64"]
      docker:
        dockerfile: Dockerfile
manifests:
  hooks:
    before:
      - host:
          command: ["sed", "-i ''", "-E", '"s/^    newTag: .+$/    newTag: $(jq .version package.json -r)/g"', "manifests/kustomization.yaml"]

  kustomize:
    paths:
      - manifests
