apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: connector-demo
  namespace: connector-demo
spec:
  timeoutSec: 30
  logging:
    enable: true
    sampleRate: 1
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 30
    healthyThreshold: 1
    unhealthyThreshold: 10
    type: HTTP
    requestPath: /
    port: 4200
